/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface LiquidationInterface extends utils.Interface {
  functions: {
    "liquidatePosition(address,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "liquidatePosition"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "liquidatePosition",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "liquidatePosition",
    data: BytesLike
  ): Result;

  events: {
    "PositionLiquidated(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PositionLiquidated"): EventFragment;
}

export interface PositionLiquidatedEventObject {
  user: string;
  amount: BigNumber;
  liquidationPrice: BigNumber;
}
export type PositionLiquidatedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  PositionLiquidatedEventObject
>;

export type PositionLiquidatedEventFilter =
  TypedEventFilter<PositionLiquidatedEvent>;

export interface Liquidation extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LiquidationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    liquidatePosition(
      user: string,
      currentPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  liquidatePosition(
    user: string,
    currentPrice: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    liquidatePosition(
      user: string,
      currentPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "PositionLiquidated(address,uint256,uint256)"(
      user?: string | null,
      amount?: null,
      liquidationPrice?: null
    ): PositionLiquidatedEventFilter;
    PositionLiquidated(
      user?: string | null,
      amount?: null,
      liquidationPrice?: null
    ): PositionLiquidatedEventFilter;
  };

  estimateGas: {
    liquidatePosition(
      user: string,
      currentPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    liquidatePosition(
      user: string,
      currentPrice: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
